/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface DeployInterface extends utils.Interface {
  functions: {
    "IS_SCRIPT()": FunctionFragment;
    "dontLog()": FunctionFragment;
    "run()": FunctionFragment;
    "vapor()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "IS_SCRIPT" | "dontLog" | "run" | "vapor"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "IS_SCRIPT", values?: undefined): string;
  encodeFunctionData(functionFragment: "dontLog", values?: undefined): string;
  encodeFunctionData(functionFragment: "run", values?: undefined): string;
  encodeFunctionData(functionFragment: "vapor", values?: undefined): string;

  decodeFunctionResult(functionFragment: "IS_SCRIPT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dontLog", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "run", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vapor", data: BytesLike): Result;

  events: {};
}

export interface Deploy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DeployInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<[boolean]>;

    dontLog(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    run(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    vapor(overrides?: CallOverrides): Promise<[string]>;
  };

  IS_SCRIPT(overrides?: CallOverrides): Promise<boolean>;

  dontLog(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  run(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

  vapor(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<boolean>;

    dontLog(overrides?: CallOverrides): Promise<void>;

    run(overrides?: CallOverrides): Promise<void>;

    vapor(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<BigNumber>;

    dontLog(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    run(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    vapor(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    dontLog(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    run(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    vapor(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
