/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface DemoGameInterface extends utils.Interface {
  functions: {
    "init(address)": FunctionFragment;
    "receiveInitialSettings(uint256,bytes)": FunctionFragment;
    "startGame(uint256,address[],bytes,bytes[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "init" | "receiveInitialSettings" | "startGame"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "init", values: [string]): string;
  encodeFunctionData(
    functionFragment: "receiveInitialSettings",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startGame",
    values: [BigNumberish, string[], BytesLike, BytesLike[]]
  ): string;

  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiveInitialSettings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startGame", data: BytesLike): Result;

  events: {};
}

export interface DemoGame extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DemoGameInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    init(
      vapor: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    receiveInitialSettings(
      sessionID: BigNumberish,
      initialSettings: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    startGame(
      sessionID: BigNumberish,
      players: string[],
      startSettings: BytesLike,
      playerSettings: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  init(
    vapor: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  receiveInitialSettings(
    sessionID: BigNumberish,
    initialSettings: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  startGame(
    sessionID: BigNumberish,
    players: string[],
    startSettings: BytesLike,
    playerSettings: BytesLike[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    init(vapor: string, overrides?: CallOverrides): Promise<void>;

    receiveInitialSettings(
      sessionID: BigNumberish,
      initialSettings: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    startGame(
      sessionID: BigNumberish,
      players: string[],
      startSettings: BytesLike,
      playerSettings: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    init(
      vapor: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    receiveInitialSettings(
      sessionID: BigNumberish,
      initialSettings: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    startGame(
      sessionID: BigNumberish,
      players: string[],
      startSettings: BytesLike,
      playerSettings: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    init(
      vapor: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    receiveInitialSettings(
      sessionID: BigNumberish,
      initialSettings: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    startGame(
      sessionID: BigNumberish,
      players: string[],
      startSettings: BytesLike,
      playerSettings: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
