/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stdStorageSol from "./StdStorage.sol";
export type { stdStorageSol };
import type * as vmSol from "./Vm.sol";
export type { vmSol };
